# TODO: Integrate systemd service

class Emacs < Formula
  desc "GNU Emacs text editor"
  homepage "https://www.gnu.org/software/emacs"
  url "https://ftpmirror.gnu.org/emacs/emacs-30.2.tar.xz"
  sha256 "b3f36f18a6dd2715713370166257de2fae01f9d38cfe878ced9b1e6ded5befd9"
  license "GPL-3.0-or-later"

  bottle do
    root_url "https://github.com/aiyazmostofa/homebrew-tap/releases/download/emacs-30.2"
    rebuild 6
    sha256 x86_64_linux: "3a9cb76926681c49a17341f1bfead338fda92a1003063dd1490039f55ee68c17"
  end

  depends_on "pkgconf" => :build

  depends_on "at-spi2-core"
  depends_on "cairo"
  depends_on "dbus"
  depends_on "fontconfig"
  depends_on "freetype"
  depends_on "gcc"
  depends_on "gdk-pixbuf"
  depends_on "glib"
  depends_on "glibc"
  depends_on "gmp"
  depends_on "gnutls"
  depends_on "gtk+3"
  depends_on "harfbuzz"
  depends_on "jpeg-turbo"
  depends_on "libgccjit"
  depends_on "libpng"
  depends_on "libtiff"
  depends_on "libxml2"
  depends_on "ncurses"
  depends_on "pango"
  depends_on "sqlite"
  depends_on "systemd"
  depends_on "tree-sitter@0.25"
  depends_on "zlib-ng-compat"

  def install
    args = std_configure_args(prefix: libexec) + %w[
      --with-pgtk
      --with-tree-sitter
      --with-native-compilation
      --with-json
    ]

    # Get libgccjit detection
    libgccjit = Formula["libgccjit"]
    libgccjit_lib = libgccjit.opt_lib/"gcc/current"
    ENV.append "LDFLAGS", "-Wl,-rpath,#{libgccjit_lib}"
    ENV.append "LIBRARY_PATH", libgccjit_lib
    ENV.append "CPATH", libgccjit.opt_include

    # Hack to make this build on immutable distros (where /home -> /var/home)
    ENV["HOMEBREW_PREFIX"] = HOMEBREW_PREFIX.realpath

    # Copied this from
    # 'https://github.com/NixOS/nixpkgs/blob/c9d1572336ba8ba2936add51ea4615a6bc1effaa/pkgs/applications/editors/emacs/make-emacs.nix'
    # to make the generated dump file hermetic.
    inreplace "src/Makefile.in", "RUN_TEMACS = ./temacs", "RUN_TEMACS = env -i ./temacs"

    system "./configure", *args
    system "make", "install"

    # A hack to make sure that GCC can be recognized by Emacs
    gcc = Formula["gcc"]
    gcc_major = gcc.version.to_s.split(".").first
    gcc_bin = libexec/"gcc-bin"
    gcc_bin.mkpath
    gcc_bin.install_symlink gcc.opt_bin/"gcc-#{gcc_major}" => "gcc"
    gcc_bin.install_symlink gcc.opt_bin/"gcc-#{gcc_major}" => "cc"
    gcc_bin.install_symlink gcc.opt_bin/"g++-#{gcc_major}" => "g++"
    gcc_bin.install_symlink gcc.opt_bin/"g++-#{gcc_major}" => "c++"

    # Binary
    (bin/"emacs").write_env_script libexec/"bin/emacs", PATH: "#{gcc_bin}:#{HOMEBREW_PREFIX}/bin:$PATH"

    # Desktop Entry
    (share/"applications").mkpath
    desktop_entry = share/"applications/emacs.desktop"
    File.write(desktop_entry, <<~EOS)
      [Desktop Entry]
      Name=Emacs
      Exec=#{bin}/emacs %F
      Icon=emacs
      Type=Application
      Terminal=false

      # Extra stuff from the default one
      GenericName=Text Editor
      Comment=Edit text
      MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
      Categories=Development;TextEditor;
      StartupNotify=true
      StartupWMClass=Emacs
    EOS
    chmod 0755, desktop_entry

    # Manpages/Icons
    man.install Dir[libexec/"share/man/*"]
    (share/"icons").install Dir[libexec/"share/icons/*"]
  end

  # Generated by AI
  def caveats
    <<~EOS
      To see Emacs in your menu, ensure "#{HOMEBREW_PREFIX}/share" is in your XDG_DATA_DIRS.
      Alternatively, symlink the desktop entry from #{opt_share}/applications/ to ~/.local/share/applications/.
      You may also need to symlink the icon from #{opt_share}/icons/ to ~/.local/share/icons/.
    EOS
  end

  # Generated by AI
  test do
    (testpath/"times-two.el").write "(defun times-two (x) (+ x x))"
    system bin/"emacs", "--batch", "-f", "batch-native-compile", "times-two.el"
    assert_equal 0, $CHILD_STATUS.exitstatus
  end
end
