# TODO: Integrate systemd service
# TODO: Add desktop integration without forcing Brew in $PATH/$XDG_DATA_DIR

class Emacs < Formula
  desc "GNU Emacs text editor"
  homepage "https://www.gnu.org/software/emacs"
  url "https://ftpmirror.gnu.org/emacs/emacs-30.2.tar.xz"
  sha256 "b3f36f18a6dd2715713370166257de2fae01f9d38cfe878ced9b1e6ded5befd9"
  license "GPL-3.0-or-later"

  bottle do
    root_url "https://github.com/aiyazmostofa/homebrew-tap/releases/download/emacs-30.2"
    rebuild 2
    sha256 x86_64_linux: "5a2442949de97fb44bfc33a51a8758f62ff99d3e6bd8d43855f250f4f124de2a"
  end

  depends_on "pkgconf" => :build

  depends_on "at-spi2-core"
  depends_on "cairo"
  depends_on "dbus"
  depends_on "fontconfig"
  depends_on "freetype"
  depends_on "gcc"
  depends_on "gdk-pixbuf"
  depends_on "glib"
  depends_on "gmp"
  depends_on "gnutls"
  depends_on "gtk+3"
  depends_on "harfbuzz"
  depends_on "jpeg-turbo"
  depends_on "libgccjit"
  depends_on "libpng"
  depends_on "libtiff"
  depends_on "libxml2"
  depends_on "ncurses"
  depends_on "pango"
  depends_on "sqlite"
  depends_on "systemd"
  depends_on "tree-sitter@0.25"
  depends_on "zlib-ng-compat"

  def install
    args = %w[
      --with-pgtk
      --with-tree-sitter
      --with-native-compilation
      --with-json
    ]

    # Get libgccjit detection
    libgccjit = Formula["libgccjit"]
    libgccjit_lib = libgccjit.opt_lib/"gcc/current"
    ENV.append "LDFLAGS", "-Wl,-rpath,#{libgccjit_lib}"
    ENV.append "LIBRARY_PATH", libgccjit_lib
    ENV.append "CPATH", libgccjit.opt_include

    # Hack to make this build on immutable distros (where /home -> /var/home)
    ENV["HOMEBREW_PREFIX"] = HOMEBREW_PREFIX.realpath

    # Copied this from
    # 'https://github.com/NixOS/nixpkgs/blob/c9d1572336ba8ba2936add51ea4615a6bc1effaa/pkgs/applications/editors/emacs/make-emacs.nix'
    # to make the generated dump file hermetic.
    inreplace "src/Makefile.in", "RUN_TEMACS = ./temacs", "RUN_TEMACS = env -i ./temacs"

    system "./configure", *args, *std_configure_args
    system "make", "install"

    # Remove files that conflict with other Brew things
    rm share/"glib-2.0/schemas/gschemas.compiled"
  end

  # Generated by AI
  test do
    (testpath/"times-two.el").write "(defun times-two (x) (+ x x))"
    system bin/"emacs", "--batch", "-f", "batch-native-compile", "times-two.el"
    assert_equal 0, $CHILD_STATUS.exitstatus
  end
end
